version: "2"

# Define services
services:
  web:
    build: .
    command: python manage.py runserver --settings=core.settings.development 0.0.0.0:8000
    # map a volume to container
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/elite_schedule_api
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
