# Generated by Django 2.1.3 on 2018-11-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('home_team', models.CharField(max_length=20)),
                ('away_team', models.CharField(max_length=20)),
                ('home_goal', models.CharField(max_length=20)),
                ('away_goal', models.CharField(max_length=20)),
                ('home_odd', models.CharField(max_length=20)),
                ('draw_odd', models.CharField(max_length=20)),
                ('away_odd', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[(1, 'ENGLAND'), (2, 'SPAIN'), (3, 'ITALY')], max_length=20)),
            ],
        ),
    ]
