# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('home_team', models.CharField(max_length=20)),
            ],
        ),
    ]
