# Generated by Django 2.1.3 on 2018-11-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='country',
        ),
    ]
