# Generated by Django 2.1.3 on 2018-11-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='div',
            new_name='division',
        ),
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='away_odds',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='draw_odds',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='home_odds',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
