# Generated by Django 2.1.3 on 2018-11-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_schedule', '0002_auto_20181125_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_goals',
            new_name='away_goal',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='away_odds',
            new_name='away_odd',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='draw_odds',
            new_name='draw_odd',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_goals',
            new_name='home_goal',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_odds',
            new_name='home_odd',
        ),
    ]
