# Generated by Django 2.1.3 on 2018-11-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_schedule', '0002_remove_match_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'managed': True, 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
    ]
