# Generated by Django 2.1.3 on 2018-11-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_schedule', '0003_auto_20181125_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_goal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_odd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='draw_odd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_odd',
            field=models.CharField(max_length=20),
        ),
    ]
